import {StyleSheet, Dimensions} from 'react-native'

export default StyleSheet.create({
    container:{
        backgroundColor: 'white',
        alignItems: "center",
        justifyContent: "center",
        height: Dimensions.get('screen').height,
        width: Dimensions.get('screen').width,
    },
    image:{
        marginTop: -80,
        width: 60,
        height: 200,
    },
    focusaText:{
        marginTop: 20,
        width: 170,
        height: 32,
    },
    ButtonStyles:{
        backgroundColor:'white', 
        marginTop: 30,
        width: 200, 
        alignItems: 'center',
        height: 40, 
        justifyContent:'center',
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 10
    },
    HostMeetingOverlayStyle:{
        alignItems: 'center',
        height: Dimensions.get('screen').height - 530,
        width: Dimensions.get('screen').width - 70,
        borderColor: 'black',
        borderWidth: 1,
    },
    JoinMeetingOverlayStyle:{
        alignItems: 'center',
        height: Dimensions.get('screen').height - 600,
        width: Dimensions.get('screen').width - 70,
        borderColor: 'black',
        borderWidth: 1,
    },
    inputBox:{
        height: 40,
        width: 250,
        borderColor: 'gray',
        borderWidth: 2,
        marginTop: 10,
        padding: 10,
        borderRadius: 17,
    },
    cancelButton:{
        alignItems: "center",
        justifyContent:"center",
        borderWidth:1,
        borderColor:"black",
        backgroundColor:"red",
        width: 90,
        height: 30,
        borderRadius: 15,
    },
    submitButton:{
        alignItems: "center",
        justifyContent:"center",
        borderWidth:1,
        borderColor:"black",
        backgroundColor:"green",
        width: 90,
        height:30,
        borderRadius: 15,
    },
})